services:
  - type: web
    name: medusa-bakend
    env: node
    region: ohio
    buildCommand: npm install && npm run build -- --filter=@dtc/backend
    startCommand: cd apps/backend && npx medusa start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: STORE_CORS
        sync: false
      - key: ADMIN_CORS
        sync: false
      - key: AUTH_CORS
        sync: false
      - key: MEDUSA_ADMIN_ONBOARDING_TYPE
        value: default
